main: lowbrain.mobs.main.LowbrainMobs
name: LowbrainMobs
version: 0.0.1
author: Lowbrain
description:
depend: [LowbrainLibrary]
softdepend: [LowbrainCore]
permission:
 lb.mobs.reload:
  description: reload config
  default: op